In [3]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [9]:
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.linear_model import LogisticRegression
from sklearn.naive_bayes import GaussianNB
from sklearn.svm import SVC
from sklearn.neighbors import KNeighborsClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score, confusion_matrix , classification_report
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score

In [4]:
df = pd.read_csv('heart_disease_full_dataset.csv')

In [5]:
df

,age,trestbps,chol,thalach,oldpeak,isMale,cp_1.0,cp_2.0,cp_3.0,cp_4.0,...,slope_2.0,slope_3.0,ca_0.0,ca_1.0,ca_2.0,ca_3.0,thal_3.0,thal_6.0,thal_7.0,class
0,0.948726,0.757525,-0.264900,0.017197,1.087338,0.686202,1.0,0.0,0.0,0.0,...,0.0,1.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0
1,1.392002,1.611220,0.760415,-1.821905,0.397182,0.686202,0.0,0.0,0.0,1.0,...,1.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,2
2,1.392002,-0.665300,-0.342283,-0.902354,1.346147,0.686202,0.0,0.0,0.0,1.0,...,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,1
3,-1.932564,-0.096170,0.063974,1.637359,2.122573,0.686202,0.0,0.0,1.0,0.0,...,0.0,1.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0
4,-1.489288,-0.096170,-0.825922,0.980537,0.310912,-1.457296,0.0,1.0,0.0,0.0,...,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
298,-1.046013,-1.234430,0.334813,-0.770990,0.138373,0.686202,1.0,0.0,0.0,0.0,...,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,1
299,1.502821,0.700612,-1.038723,-0.376896,2.036303,0.686202,0.0,0.0,0.0,1.0,...,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,2
300,0.283813,-0.096170,-2.238149,-1.515388,0.138373,0.686202,0.0,0.0,0.0,1.0,...,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,3
301,0.283813,-0.096170,-0.206864,1.068113,-0.896862,-1.457296,0.0,1.0,0.0,0.0,...,1.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,1
302,-1.821745,0.359134,-1.386944,1.024325,-0.896862,0.686202,0.0,0.0,1.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0

In [6]:
df.head()

,age,trestbps,chol,thalach,oldpeak,isMale,cp_1.0,cp_2.0,cp_3.0,cp_4.0,...,slope_2.0,slope_3.0,ca_0.0,ca_1.0,ca_2.0,ca_3.0,thal_3.0,thal_6.0,thal_7.0,class
0,0.948726,0.757525,-0.264900,0.017197,1.087338,0.686202,1.0,0.0,0.0,0.0,...,0.0,1.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0
1,1.392002,1.611220,0.760415,-1.821905,0.397182,0.686202,0.0,0.0,0.0,1.0,...,1.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,2
2,1.392002,-0.665300,-0.342283,-0.902354,1.346147,0.686202,0.0,0.0,0.0,1.0,...,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,1
3,-1.932564,-0.096170,0.063974,1.637359,2.122573,0.686202,0.0,0.0,1.0,0.0,...,0.0,1.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0
4,-1.489288,-0.096170,-0.825922,0.980537,0.310912,-1.457296,0.0,1.0,0.0,0.0,...,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0

In [7]:
df.columns

Index(['age', 'trestbps', 'chol', 'thalach', 'oldpeak', 'isMale', 'cp_1.0',
       'cp_2.0', 'cp_3.0', 'cp_4.0', 'fbs_0.0', 'fbs_1.0', 'restecg_0.0',
       'restecg_1.0', 'restecg_2.0', 'exang_0.0', 'exang_1.0', 'slope_1.0',
       'slope_2.0', 'slope_3.0', 'ca_0.0', 'ca_1.0', 'ca_2.0', 'ca_3.0',
       'thal_3.0', 'thal_6.0', 'thal_7.0', 'class'],
      dtype='object')

# Train Test Split

In [12]:
X = df.drop('class',axis=1)
Y = df['class']

In [13]:
X_train, X_test, y_train, y_test = train_test_split(X, Y, test_size=0.20, random_state=42)

# Linear Regression

In [11]:
model = LinearRegression()
model

LinearRegression()

In [14]:
model.fit(X_train,y_train)

LinearRegression()

In [15]:
y_pred = model.predict(X_test)

In [16]:
y_pred

array([ 9.70743638e-01,  1.36587362e+00,  1.66169778e+00,  9.17982936e-01,
        1.28245375e+00,  1.95365856e+00,  2.23909161e+00,  2.74848330e+00,
        8.35528332e-01,  1.10245236e+00, -4.99897533e-02, -4.31104954e-01,
        1.43204606e+00,  2.28054548e+00,  2.56158251e+00, -1.25519770e-01,
        2.36815731e-01,  1.42814984e+00,  2.88123635e+00,  4.68981690e-01,
        8.00969128e-01, -1.46023612e-01,  2.80211748e+00,  9.50701873e-02,
        2.81418716e+00, -8.78657686e-02,  7.69003869e-01,  1.24550163e+00,
        2.27868263e+00,  1.31317741e+00,  7.63337459e-01,  1.16469112e+00,
       -1.71300343e-01,  8.14137159e-01,  5.75210501e-01,  1.15211546e+00,
        2.33377977e+00,  7.53237231e-01,  2.77880024e+00,  7.25955578e-01,
        1.89467149e+00,  5.93860035e-01,  1.65747847e+00, -4.42542537e-04,
        2.81709770e-01,  2.10426823e+00, -2.21280826e-01,  4.12656906e-01,
        1.17203759e+00,  1.10152677e+00,  3.81988469e-01, -2.37264773e-01,
       -3.77398483e-01,  8.69440890e-02,  1.82316975e+00,  5.91334754e-01,
        1.27501631e-01,  1.93600071e+00,  1.91178855e+00,  1.99968328e+00,
        3.34602072e-01])

In [18]:
r2 = r2_score(y_test,y_pred)
r2

0.5822858104275789

# LogisticRegression

In [19]:
model = LogisticRegression(max_iter=500)
model

LogisticRegression(max_iter=500)

In [20]:
model.fit(X_train,y_train)

LogisticRegression(max_iter=500)

In [21]:
y_pred = model.predict(X_test)
y_pred

array([0, 1, 2, 1, 1, 3, 2, 3, 0, 1, 0, 0, 1, 3, 2, 0, 0, 3, 2, 0, 1, 0,
       3, 0, 3, 0, 1, 0, 3, 1, 0, 1, 0, 0, 0, 0, 2, 1, 3, 0, 1, 0, 1, 0,
       0, 2, 0, 0, 0, 0, 0, 0, 0, 0, 3, 0, 0, 0, 1, 2, 0])

In [22]:
y_test

179    0
228    3
111    1
246    2
60     2
      ..
249    0
104    3
300    3
193    2
184    1
Name: class, Length: 61, dtype: int64

In [23]:
confusion_matrix(y_test,y_pred)

array([[24,  5,  0,  0,  0],
       [ 6,  0,  3,  3,  0],
       [ 1,  3,  2,  3,  0],
       [ 1,  4,  1,  1,  0],
       [ 0,  1,  1,  2,  0]])

In [24]:
accuracy_score(y_test,y_pred)

0.4426229508196721

In [25]:
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           0       0.75      0.83      0.79        29
           1       0.00      0.00      0.00        12
           2       0.29      0.22      0.25         9
           3       0.11      0.14      0.12         7
           4       0.00      0.00      0.00         4

    accuracy                           0.44        61
   macro avg       0.23      0.24      0.23        61
weighted avg       0.41      0.44      0.43        61

C:\Python313\Lib\site-packages\sklearn\metrics\_classification.py:1731: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
C:\Python313\Lib\site-packages\sklearn\metrics\_classification.py:1731: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
C:\Python313\Lib\site-packages\sklearn\metrics\_classification.py:1731: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])

# KNN

In [28]:
knn_model = KNeighborsClassifier(n_neighbors= 5)
knn_model

KNeighborsClassifier()

In [29]:
knn_model.fit(X_train,y_train)

KNeighborsClassifier()

In [30]:
y_pred_knn = knn_model.predict(X_test)

In [31]:
y_pred_knn

array([0, 1, 2, 0, 1, 1, 1, 3, 0, 0, 0, 0, 2, 1, 3, 0, 0, 3, 2, 0, 0, 0,
       2, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 3, 1, 3, 1, 0, 0, 0, 2, 0,
       0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 3, 0, 0])

In [32]:
y_test

179    0
228    3
111    1
246    2
60     2
      ..
249    0
104    3
300    3
193    2
184    1
Name: class, Length: 61, dtype: int64

In [33]:
confusion_matrix(y_test,y_pred_knn)

array([[28,  0,  0,  1,  0],
       [ 4,  5,  1,  2,  0],
       [ 4,  4,  1,  0,  0],
       [ 1,  2,  1,  3,  0],
       [ 0,  2,  2,  0,  0]])

In [34]:
accuracy_score(y_test,y_pred_knn)

0.6065573770491803

In [35]:
print(classification_report(y_test,y_pred_knn))

              precision    recall  f1-score   support

           0       0.76      0.97      0.85        29
           1       0.38      0.42      0.40        12
           2       0.20      0.11      0.14         9
           3       0.50      0.43      0.46         7
           4       0.00      0.00      0.00         4

    accuracy                           0.61        61
   macro avg       0.37      0.38      0.37        61
weighted avg       0.52      0.61      0.56        61

C:\Python313\Lib\site-packages\sklearn\metrics\_classification.py:1731: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
C:\Python313\Lib\site-packages\sklearn\metrics\_classification.py:1731: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
C:\Python313\Lib\site-packages\sklearn\metrics\_classification.py:1731: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])

# Decision Tree

In [37]:
model_DT = DecisionTreeClassifier(random_state=42)
model_DT

DecisionTreeClassifier(random_state=42)

In [38]:
model_DT.fit(X_train,y_train)

DecisionTreeClassifier(random_state=42)

In [39]:
y_pred_DT = model_DT.predict(X_test)

In [40]:
y_pred_DT

array([0, 0, 1, 2, 1, 2, 4, 1, 0, 3, 0, 0, 1, 1, 1, 0, 0, 3, 3, 0, 1, 0,
       3, 0, 2, 0, 2, 3, 2, 1, 0, 2, 0, 0, 0, 1, 1, 0, 1, 0, 2, 0, 2, 0,
       2, 1, 0, 0, 0, 0, 1, 0, 0, 0, 3, 0, 0, 2, 2, 4, 1])

In [41]:
y_test

179    0
228    3
111    1
246    2
60     2
      ..
249    0
104    3
300    3
193    2
184    1
Name: class, Length: 61, dtype: int64

In [42]:
confusion_matrix(y_test,y_pred_DT)

array([[23,  2,  3,  1,  0],
       [ 3,  6,  1,  2,  0],
       [ 1,  1,  3,  2,  2],
       [ 1,  3,  3,  0,  0],
       [ 0,  2,  1,  1,  0]])

In [43]:
accuracy_score(y_test,y_pred_DT)

0.5245901639344263

In [44]:
print(classification_report(y_test,y_pred_DT))

              precision    recall  f1-score   support

           0       0.82      0.79      0.81        29
           1       0.43      0.50      0.46        12
           2       0.27      0.33      0.30         9
           3       0.00      0.00      0.00         7
           4       0.00      0.00      0.00         4

    accuracy                           0.52        61
   macro avg       0.30      0.33      0.31        61
weighted avg       0.52      0.52      0.52        61

# Naive Bayes

In [45]:
model_NB = GaussianNB()
model_NB

GaussianNB()

In [46]:
model_NB.fit(X_train,y_train)

GaussianNB()

In [47]:
y_pred_NB = model_NB.predict(X_test)
y_pred_NB

array([2, 4, 2, 4, 4, 3, 4, 4, 4, 4, 1, 4, 1, 4, 3, 1, 1, 3, 3, 4, 2, 0,
       4, 1, 3, 0, 4, 4, 3, 4, 2, 4, 0, 1, 4, 4, 4, 4, 4, 4, 2, 1, 1, 0,
       4, 4, 0, 1, 4, 1, 4, 0, 0, 0, 3, 4, 0, 2, 4, 2, 4])

In [48]:
y_test

179    0
228    3
111    1
246    2
60     2
      ..
249    0
104    3
300    3
193    2
184    1
Name: class, Length: 61, dtype: int64

In [49]:
confusion_matrix(y_test,y_pred_NB)

array([[9, 7, 4, 0, 9],
       [0, 1, 1, 2, 8],
       [0, 0, 1, 2, 6],
       [0, 1, 1, 1, 4],
       [0, 1, 0, 2, 1]])

In [50]:
accuracy_score(y_test,y_pred_NB)

0.21311475409836064

In [51]:
print(classification_report(y_test,y_pred_NB))

              precision    recall  f1-score   support

           0       1.00      0.31      0.47        29
           1       0.10      0.08      0.09        12
           2       0.14      0.11      0.12         9
           3       0.14      0.14      0.14         7
           4       0.04      0.25      0.06         4

    accuracy                           0.21        61
   macro avg       0.28      0.18      0.18        61
weighted avg       0.53      0.21      0.28        61

# Support Vector Machine

In [52]:
model_svm = SVC(kernel = 'linear')
model_svm

SVC(kernel='linear')

In [53]:
model_svm.fit(X_train, y_train)

SVC(kernel='linear')

In [54]:
y_pred_svc = model_svm.predict(X_test)

In [55]:
y_pred

array([0, 1, 2, 1, 1, 3, 2, 3, 0, 1, 0, 0, 1, 3, 2, 0, 0, 3, 2, 0, 1, 0,
       3, 0, 3, 0, 1, 0, 3, 1, 0, 1, 0, 0, 0, 0, 2, 1, 3, 0, 1, 0, 1, 0,
       0, 2, 0, 0, 0, 0, 0, 0, 0, 0, 3, 0, 0, 0, 1, 2, 0])

In [56]:
y_test

179    0
228    3
111    1
246    2
60     2
      ..
249    0
104    3
300    3
193    2
184    1
Name: class, Length: 61, dtype: int64

In [57]:
confusion_matrix(y_test,y_pred_svc)

array([[25,  3,  1,  0,  0],
       [ 5,  0,  3,  4,  0],
       [ 2,  2,  2,  3,  0],
       [ 0,  4,  2,  1,  0],
       [ 0,  1,  0,  2,  1]])

In [58]:
accuracy_score(y_test,y_pred_svc)

0.47540983606557374