In [90]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.linear_model import LogisticRegression
from sklearn.naive_bayes import GaussianNB
from sklearn.svm import SVC
from sklearn.neighbors import KNeighborsClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score, confusion_matrix , classification_report
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score

In [91]:
df = pd.read_csv('heart_disease_selected_dataset.csv')

In [92]:
df

,oldpeak,isMale,age,trestbps,chol,thalach,thal_3.0,cp_4.0,thal_7.0,ca_0.0,...,slope_2.0,ca_2.0,ca_3.0,cp_3.0,cp_2.0,ca_1.0,restecg_0.0,restecg_2.0,thal_6.0,class
0,1.087338,0.686202,0.948726,0.757525,-0.264900,0.017197,0.0,0.0,0.0,1.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,0
1,0.397182,0.686202,1.392002,1.611220,0.760415,-1.821905,1.0,1.0,0.0,0.0,...,1.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,2
2,1.346147,0.686202,1.392002,-0.665300,-0.342283,-0.902354,0.0,1.0,1.0,0.0,...,1.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1
3,2.122573,0.686202,-1.932564,-0.096170,0.063974,1.637359,1.0,0.0,0.0,1.0,...,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0
4,0.310912,-1.457296,-1.489288,-0.096170,-0.825922,0.980537,1.0,0.0,0.0,1.0,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
298,0.138373,0.686202,-1.046013,-1.234430,0.334813,-0.770990,0.0,0.0,1.0,1.0,...,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1
299,2.036303,0.686202,1.502821,0.700612,-1.038723,-0.376896,0.0,1.0,1.0,0.0,...,1.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,2
300,0.138373,0.686202,0.283813,-0.096170,-2.238149,-1.515388,0.0,1.0,1.0,0.0,...,1.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,3
301,-0.896862,-1.457296,0.283813,-0.096170,-0.206864,1.068113,1.0,0.0,0.0,0.0,...,1.0,0.0,0.0,0.0,1.0,1.0,0.0,1.0,0.0,1
302,-0.896862,0.686202,-1.821745,0.359134,-1.386944,1.024325,1.0,0.0,0.0,0.0,...,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0

In [93]:
df.head()

,oldpeak,isMale,age,trestbps,chol,thalach,thal_3.0,cp_4.0,thal_7.0,ca_0.0,...,slope_2.0,ca_2.0,ca_3.0,cp_3.0,cp_2.0,ca_1.0,restecg_0.0,restecg_2.0,thal_6.0,class
0,1.087338,0.686202,0.948726,0.757525,-0.264900,0.017197,0.0,0.0,0.0,1.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,0
1,0.397182,0.686202,1.392002,1.611220,0.760415,-1.821905,1.0,1.0,0.0,0.0,...,1.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,2
2,1.346147,0.686202,1.392002,-0.665300,-0.342283,-0.902354,0.0,1.0,1.0,0.0,...,1.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1
3,2.122573,0.686202,-1.932564,-0.096170,0.063974,1.637359,1.0,0.0,0.0,1.0,...,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0
4,0.310912,-1.457296,-1.489288,-0.096170,-0.825922,0.980537,1.0,0.0,0.0,1.0,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0

In [94]:
df.columns

Index(['oldpeak', 'isMale', 'age', 'trestbps', 'chol', 'thalach', 'thal_3.0',
       'cp_4.0', 'thal_7.0', 'ca_0.0', 'exang_0.0', 'exang_1.0', 'slope_1.0',
       'slope_2.0', 'ca_2.0', 'ca_3.0', 'cp_3.0', 'cp_2.0', 'ca_1.0',
       'restecg_0.0', 'restecg_2.0', 'thal_6.0', 'class'],
      dtype='object')

# Train Test Split

In [95]:
X = df.drop('class',axis=1)
Y = df['class']
X_train, X_test, y_train, y_test = train_test_split(X, Y, test_size=0.20, random_state=42)

# Linear Regression

In [96]:
model = LinearRegression()
model

LinearRegression()

In [97]:
model.fit(X_train,y_train)

LinearRegression()

In [98]:
y_pred = model.predict(X_test)
y_pred

array([ 0.92080928,  1.36591287,  1.60176453,  0.92252347,  1.28471901,
        1.90106515,  2.24074396,  2.76164173,  0.84379541,  1.10794961,
       -0.0481564 , -0.4268281 ,  1.44063213,  2.28904376,  2.5029456 ,
       -0.12123816,  0.23779695,  1.36118707,  2.88602967,  0.4681954 ,
        0.80605329, -0.13713303,  2.81841986,  0.09934689,  2.76087463,
       -0.08575356,  0.76421942,  1.27052152,  2.27154168,  1.31173676,
        0.70458359,  1.17769007, -0.17158932,  0.83841509,  0.57512016,
        1.15427233,  2.33530238,  0.75067848,  2.79332517,  0.72576453,
        1.90704602,  0.60257802,  1.66178717, -0.05039218,  0.28062983,
        2.10977257, -0.2113722 ,  0.41511593,  1.18802251,  1.10723269,
        0.38390133, -0.22942953, -0.42770482,  0.0956428 ,  1.77012682,
        0.59267813,  0.06947857,  1.94514435,  1.91905778,  1.93706257,
        0.33849502])

In [99]:
r2 = r2_score(y_test,y_pred)
r2

0.5842452493419161

# LogisticRegression

In [100]:
model = LogisticRegression(max_iter=500)
model

LogisticRegression(max_iter=500)

In [101]:
model.fit(X_train,y_train)

LogisticRegression(max_iter=500)

In [102]:
y_pred = model.predict(X_test)
y_pred

array([0, 1, 1, 1, 1, 3, 2, 3, 0, 1, 0, 0, 1, 3, 2, 0, 0, 3, 2, 0, 1, 0,
       3, 0, 3, 0, 1, 2, 3, 1, 0, 1, 0, 0, 0, 0, 2, 1, 3, 0, 2, 0, 1, 0,
       0, 2, 0, 0, 0, 0, 0, 0, 0, 0, 3, 0, 0, 0, 3, 1, 0])

In [103]:
y_test

179    0
228    3
111    1
246    2
60     2
      ..
249    0
104    3
300    3
193    2
184    1
Name: class, Length: 61, dtype: int64

In [104]:
confusion_matrix(y_test,y_pred)

array([[24,  4,  1,  0,  0],
       [ 5,  1,  3,  3,  0],
       [ 1,  4,  1,  3,  0],
       [ 1,  3,  1,  2,  0],
       [ 0,  1,  1,  2,  0]])

In [105]:
accuracy_score(y_test,y_pred)

0.45901639344262296

In [106]:
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           0       0.77      0.83      0.80        29
           1       0.08      0.08      0.08        12
           2       0.14      0.11      0.12         9
           3       0.20      0.29      0.24         7
           4       0.00      0.00      0.00         4

    accuracy                           0.46        61
   macro avg       0.24      0.26      0.25        61
weighted avg       0.43      0.46      0.44        61

C:\Python313\Lib\site-packages\sklearn\metrics\_classification.py:1731: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
C:\Python313\Lib\site-packages\sklearn\metrics\_classification.py:1731: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
C:\Python313\Lib\site-packages\sklearn\metrics\_classification.py:1731: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])

# KNN

In [107]:
knn_model = KNeighborsClassifier(n_neighbors= 5)
knn_model

KNeighborsClassifier()

In [108]:
knn_model.fit(X_train,y_train)

KNeighborsClassifier()

In [109]:
y_pred_knn = knn_model.predict(X_test)
y_pred_knn

array([0, 2, 2, 0, 1, 1, 1, 3, 0, 0, 0, 0, 2, 1, 3, 0, 0, 3, 2, 0, 0, 0,
       2, 0, 4, 0, 0, 2, 2, 1, 0, 0, 0, 0, 0, 3, 1, 1, 1, 0, 2, 0, 2, 0,
       0, 2, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 3, 0, 0])

In [110]:
y_test

179    0
228    3
111    1
246    2
60     2
      ..
249    0
104    3
300    3
193    2
184    1
Name: class, Length: 61, dtype: int64

In [111]:
confusion_matrix(y_test,y_pred_knn)

array([[27,  1,  1,  0,  0],
       [ 4,  3,  3,  2,  0],
       [ 4,  3,  2,  0,  0],
       [ 0,  2,  2,  3,  0],
       [ 0,  1,  2,  0,  1]])

In [112]:
accuracy_score(y_test,y_pred_knn)

0.5901639344262295

In [69]:
print(classification_report(y_test,y_pred_knn))

              precision    recall  f1-score   support

           0       0.77      0.93      0.84        29
           1       0.30      0.25      0.27        12
           2       0.20      0.22      0.21         9
           3       0.60      0.43      0.50         7
           4       1.00      0.25      0.40         4

    accuracy                           0.59        61
   macro avg       0.57      0.42      0.45        61
weighted avg       0.59      0.59      0.57        61

# Decision Tree

In [113]:
model_DT = DecisionTreeClassifier(random_state=42)
model_DT

DecisionTreeClassifier(random_state=42)

In [114]:
model_DT.fit(X_train,y_train)

DecisionTreeClassifier(random_state=42)

In [115]:
y_pred_DT = model_DT.predict(X_test)
y_pred_DT

array([0, 1, 0, 2, 1, 1, 3, 3, 0, 3, 0, 0, 1, 1, 1, 0, 0, 3, 2, 0, 1, 0,
       3, 0, 4, 0, 2, 0, 2, 1, 0, 3, 0, 0, 0, 0, 2, 0, 1, 0, 2, 0, 2, 0,
       2, 3, 0, 0, 0, 0, 1, 0, 0, 0, 3, 0, 0, 2, 1, 1, 1])

In [116]:
y_test

179    0
228    3
111    1
246    2
60     2
      ..
249    0
104    3
300    3
193    2
184    1
Name: class, Length: 61, dtype: int64

In [117]:
confusion_matrix(y_test,y_pred_DT)

array([[23,  2,  3,  1,  0],
       [ 6,  3,  1,  2,  0],
       [ 1,  2,  2,  4,  0],
       [ 0,  4,  2,  1,  0],
       [ 0,  2,  1,  0,  1]])

In [118]:
accuracy_score(y_test,y_pred_DT)

0.4918032786885246

In [119]:
print(classification_report(y_test,y_pred_DT))

              precision    recall  f1-score   support

           0       0.77      0.79      0.78        29
           1       0.23      0.25      0.24        12
           2       0.22      0.22      0.22         9
           3       0.12      0.14      0.13         7
           4       1.00      0.25      0.40         4

    accuracy                           0.49        61
   macro avg       0.47      0.33      0.36        61
weighted avg       0.52      0.49      0.49        61

# Naive Bayes

In [120]:
model_NB = GaussianNB()
model_NB

GaussianNB()

In [121]:
model_NB.fit(X_train,y_train)

GaussianNB()

In [122]:
y_pred_NB = model_NB.predict(X_test)
y_pred_NB

array([1, 4, 4, 4, 4, 4, 4, 4, 4, 4, 0, 0, 1, 4, 4, 0, 0, 4, 4, 4, 0, 0,
       4, 0, 4, 0, 4, 4, 4, 4, 0, 4, 0, 0, 4, 4, 4, 4, 4, 4, 2, 0, 1, 0,
       4, 4, 0, 0, 4, 2, 4, 0, 0, 0, 4, 4, 0, 2, 4, 4, 4])

In [123]:
y_test

179    0
228    3
111    1
246    2
60     2
      ..
249    0
104    3
300    3
193    2
184    1
Name: class, Length: 61, dtype: int64

In [124]:
confusion_matrix(y_test,y_pred_NB)

array([[19,  1,  1,  0,  8],
       [ 0,  0,  1,  0, 11],
       [ 0,  0,  0,  0,  9],
       [ 0,  1,  1,  0,  5],
       [ 0,  1,  0,  0,  3]])

In [125]:
accuracy_score(y_test,y_pred_NB)

0.36065573770491804

In [126]:
print(classification_report(y_test,y_pred_NB))

              precision    recall  f1-score   support

           0       1.00      0.66      0.79        29
           1       0.00      0.00      0.00        12
           2       0.00      0.00      0.00         9
           3       0.00      0.00      0.00         7
           4       0.08      0.75      0.15         4

    accuracy                           0.36        61
   macro avg       0.22      0.28      0.19        61
weighted avg       0.48      0.36      0.39        61

C:\Python313\Lib\site-packages\sklearn\metrics\_classification.py:1731: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
C:\Python313\Lib\site-packages\sklearn\metrics\_classification.py:1731: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
C:\Python313\Lib\site-packages\sklearn\metrics\_classification.py:1731: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])

# Support Vector Machine

In [127]:
model_svm = SVC(kernel = 'linear')
model_svm

SVC(kernel='linear')

In [128]:
model_svm.fit(X_train, y_train)

SVC(kernel='linear')

In [129]:
y_pred_svc = model_svm.predict(X_test)
y_pred

array([0, 1, 1, 1, 1, 3, 2, 3, 0, 1, 0, 0, 1, 3, 2, 0, 0, 3, 2, 0, 1, 0,
       3, 0, 3, 0, 1, 2, 3, 1, 0, 1, 0, 0, 0, 0, 2, 1, 3, 0, 2, 0, 1, 0,
       0, 2, 0, 0, 0, 0, 0, 0, 0, 0, 3, 0, 0, 0, 3, 1, 0])

In [130]:
y_test

179    0
228    3
111    1
246    2
60     2
      ..
249    0
104    3
300    3
193    2
184    1
Name: class, Length: 61, dtype: int64

In [131]:
confusion_matrix(y_test,y_pred_svc)

array([[25,  3,  1,  0,  0],
       [ 6,  1,  2,  3,  0],
       [ 1,  3,  2,  3,  0],
       [ 0,  4,  2,  1,  0],
       [ 0,  1,  0,  2,  1]])

In [132]:
accuracy_score(y_test,y_pred_svc)

0.4918032786885246